"""
Specum design stage.

Transforms requirements into technical design:
schema definitions, API contracts, component hierarchies, integration points.
Uses the ArchitectAgent persona.
"""

from __future__ import annotations

from datetime import datetime
from typing import Optional


class DesignStage:
    """
    Technical design stage using an ArchitectAgent persona.

    Consumes the requirements artifact and produces a design.md with:
    - Component architecture diagram (Mermaid)
    - Data model and schema definitions
    - API contract specifications
    - Integration points and boundaries
    - Technology decisions with rationale

    The output of this stage becomes the input for the TaskStage.
    """

    PERSONA = "ArchitectAgent"

    def __init__(self, goal: str, requirements_artifact: Optional[str] = None) -> None:
        """
        Initialize the design stage.

        Args:
            goal: The high-level goal being implemented.
            requirements_artifact: Content of the requirements.md from the previous stage.
        """
        self.goal = goal
        self.requirements = requirements_artifact or ""
        self.generated_at = datetime.utcnow()

    def generate(self) -> str:
        """
        Generate the design artifact.

        Returns:
            Design artifact as a markdown string with Mermaid diagrams.
        """
        return self._render_design()

    def _render_design(self) -> str:
        """Render the technical design document."""
        return f"""# Technical Design

**Generated by:** {self.PERSONA}
**Date:** {self.generated_at.strftime('%Y-%m-%d %H:%M UTC')}
**Goal:** {self.goal}

---

## Architecture Overview

```mermaid
graph TB
    Client["Client / Consumer"]
    API["API Layer"]
    Service["Service Layer"]
    Domain["Domain / Business Logic"]
    Repository["Repository Layer"]
    DB[("Database")]
    Cache[("Cache")]
    ExternalServices["External Services"]

    Client -->|HTTP/gRPC| API
    API --> Service
    Service --> Domain
    Service --> Repository
    Repository --> DB
    Repository --> Cache
    Service --> ExternalServices

    style Domain fill:#f9f,stroke:#333,stroke-width:2px
    style API fill:#bbf,stroke:#333,stroke-width:2px
```

## Component Responsibilities

### API Layer
- Request validation and sanitization
- Authentication and authorization checks
- Response serialization
- Rate limiting
- Error response formatting

### Service Layer
- Orchestration of business operations
- Transaction management
- Event publishing
- External service integration

### Domain Layer
- Business rules and invariants
- Domain model entities and value objects
- Domain events
- No dependencies on infrastructure

### Repository Layer
- Data access abstraction
- Query optimization
- Caching strategy
- Pagination

## Data Model

```mermaid
erDiagram
    Entity {{
        string id PK
        string name
        datetime created_at
        datetime updated_at
        string status
    }}

    RelatedEntity {{
        string id PK
        string entity_id FK
        string type
        json metadata
        datetime created_at
    }}

    Entity ||--o{{ RelatedEntity : "has many"
```

### Schema Definitions

```sql
-- Primary entity table
CREATE TABLE entities (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name        VARCHAR(255) NOT NULL,
    status      VARCHAR(50) NOT NULL DEFAULT 'active',
    metadata    JSONB DEFAULT '{{}}',
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for common query patterns
CREATE INDEX idx_entities_status ON entities(status);
CREATE INDEX idx_entities_created_at ON entities(created_at DESC);
```

## API Contract

### REST Endpoints

#### Create Entity
```
POST /api/v1/entities
Content-Type: application/json
Authorization: Bearer <token>

Request:
{{
  "name": "string (required, 1-255 chars)",
  "metadata": {{}} (optional)
}}

Response 201:
{{
  "id": "uuid",
  "name": "string",
  "status": "active",
  "created_at": "ISO 8601 datetime"
}}

Response 400 (validation error):
{{
  "error": "VALIDATION_ERROR",
  "message": "name is required",
  "fields": {{"name": "required"}}
}}
```

#### Get Entity
```
GET /api/v1/entities/:id
Authorization: Bearer <token>

Response 200:
{{
  "id": "uuid",
  "name": "string",
  "status": "active",
  "metadata": {{}},
  "created_at": "ISO 8601 datetime",
  "updated_at": "ISO 8601 datetime"
}}

Response 404:
{{
  "error": "NOT_FOUND",
  "message": "Entity not found"
}}
```

#### List Entities
```
GET /api/v1/entities?status=active&page=1&per_page=20
Authorization: Bearer <token>

Response 200:
{{
  "data": [...],
  "meta": {{
    "total": 100,
    "page": 1,
    "per_page": 20,
    "total_pages": 5
  }}
}}
```

## Integration Points

| Integration | Type | Protocol | Auth | Notes |
|------------|------|----------|------|-------|
| Database | Synchronous | SQL/TCP | Connection pool | Primary persistence |
| Cache | Synchronous | Redis protocol | None (internal) | TTL: 5 minutes |
| Message Queue | Asynchronous | AMQP | mTLS | For domain events |
| Auth Service | Synchronous | HTTP/JWT | Service account | Token validation |

## Technology Decisions

| Decision | Choice | Rationale | Alternatives Considered |
|---------|--------|-----------|------------------------|
| Database | PostgreSQL | ACID compliance, JSONB support, mature | MySQL, MongoDB |
| Cache | Redis | Simple, fast, pub/sub support | Memcached, in-memory |
| API style | REST | Team familiarity, tooling support | GraphQL, gRPC |
| Auth | JWT | Stateless, widely supported | Session cookies, OAuth |

## Security Design

- All endpoints require authentication except public health checks
- Authorization: role-based (admin, user, readonly)
- Input validation at API layer before any processing
- Secrets via environment variables, never in code
- All SQL queries parameterized (no string interpolation)
- Rate limiting: 100 req/min per user, 1000 req/min per IP

## Error Handling Strategy

```
Infrastructure errors (DB, cache, network) → Log with correlation ID → Return 503
Validation errors → Return 400 with field-specific messages
Not found → Return 404 with resource type
Auth errors → Return 401/403 (never leak which)
Business rule violations → Return 422 with specific error code
Unexpected errors → Return 500, log with full stack trace, alert on-call
```

---

*This document was produced by the Specum design stage.*
*Review data model and API contracts before advancing to the Tasks stage.*
"""
