"""
Specum implement stage.

Executes the task list from the tasks stage using a Ralph Loop
for persistence, ensuring implementation doesn't stop until complete.
Uses the ExecutorAgent persona.
"""

from __future__ import annotations

from datetime import datetime
from typing import Optional


class ImplementStage:
    """
    Implementation execution stage using an ExecutorAgent persona.

    Consumes the tasks.md artifact and executes tasks sequentially,
    using the Ralph Loop to ensure persistence across interruptions.

    Each task is executed, verified, and committed before moving to the next.
    The output is an implementation-report.md with evidence of completion.
    """

    PERSONA = "ExecutorAgent"

    def __init__(self, goal: str, tasks_artifact: Optional[str] = None) -> None:
        """
        Initialize the implement stage.

        Args:
            goal: The high-level goal being implemented.
            tasks_artifact: Content of tasks.md from the previous stage.
        """
        self.goal = goal
        self.tasks = tasks_artifact or ""
        self.generated_at = datetime.utcnow()

    def generate(self) -> str:
        """
        Generate the implementation report artifact.

        In a real integration this would spawn a RalphLoop and execute
        tasks one by one, collecting evidence. Here we produce the
        implementation report template with execution guidance.

        Returns:
            Implementation report as a markdown string.
        """
        return self._render_implementation_report()

    def _render_implementation_report(self) -> str:
        """Render the implementation report document."""
        return f"""# Implementation Report

**Generated by:** {self.PERSONA}
**Date:** {self.generated_at.strftime('%Y-%m-%d %H:%M UTC')}
**Goal:** {self.goal}
**Mode:** Ralph Loop (persistent iterative execution)

---

## Execution Summary

The implementation stage uses the Ralph Loop to enforce completion.
Each task is executed, verified, and logged before advancing.

```
ralph = RalphLoop()
ralph.start(goal="{self.goal}", max_iterations=100)

while not ralph.state.should_stop():
    ralph.iterate(task_runner=executor_agent)
```

---

## Phase 1: Foundation

### Task 1.1: Proof-of-concept spike
- **Status:** [ ] PENDING / [x] IN PROGRESS / [ ] COMPLETE
- **Result:** [Document spike outcome here]
- **Decision:** PROCEED / PIVOT
- **Evidence:** [Link to spike output]

### Task 1.2: Project scaffolding
- **Status:** [ ] PENDING / [ ] IN PROGRESS / [ ] COMPLETE
- **Evidence:** `build output here`
- **CI Status:** [Green/Red]

### Task 1.3: Database schema and migration
- **Status:** [ ] PENDING / [ ] IN PROGRESS / [ ] COMPLETE
- **Migration files created:** [List migration file names]
- **Schema applied:** [Yes/No, with timestamp]

### Task 1.4: Repository layer
- **Status:** [ ] PENDING / [ ] IN PROGRESS / [ ] COMPLETE
- **Files created:** [List repository files]

---

## Phase 2: Core Business Logic

### Task 2.1: Domain model and business rules
- **Status:** [ ] PENDING / [ ] IN PROGRESS / [ ] COMPLETE
- **Domain entities created:** [List entities]
- **Business rules validated:** [List rules with pass/fail]

### Task 2.2: Service layer orchestration
- **Status:** [ ] PENDING / [ ] IN PROGRESS / [ ] COMPLETE
- **Services created:** [List service classes]

### Task 2.3: Error handling and validation
- **Status:** [ ] PENDING / [ ] IN PROGRESS / [ ] COMPLETE
- **Error types defined:** [List error types]

---

## Phase 3: API Layer

### Task 3.1: API routing and middleware
- **Status:** [ ] PENDING / [ ] IN PROGRESS / [ ] COMPLETE
- **Middleware stack:** [List middleware in order]

### Task 3.2: Implement API endpoints
- **Status:** [ ] PENDING / [ ] IN PROGRESS / [ ] COMPLETE
- **Endpoints implemented:** [List endpoints]

### Task 3.3: API error responses
- **Status:** [ ] PENDING / [ ] IN PROGRESS / [ ] COMPLETE
- **Error scenarios covered:** [List scenarios]

---

## Phase 4: Integration and Quality

### Task 4.1: End-to-end integration test
- **Status:** [ ] PENDING / [ ] IN PROGRESS / [ ] COMPLETE
- **E2E scenario result:** PASS / FAIL
- **Evidence:** [Screenshot or log output]

### Task 4.2: Observability
- **Status:** [ ] PENDING / [ ] IN PROGRESS / [ ] COMPLETE
- **Health endpoint:** [URL]
- **Metrics:** [List key metrics]

### Task 4.3: Performance validation
- **Status:** [ ] PENDING / [ ] IN PROGRESS / [ ] COMPLETE
- **Load test results:** [p50, p95, p99 latencies]
- **Max throughput:** [req/sec]

### Task 4.4: Documentation
- **Status:** [ ] PENDING / [ ] IN PROGRESS / [ ] COMPLETE
- **Docs location:** [Path or URL]

---

## Ralph Loop Execution Log

```
[RALPH LOOP - ITERATION 1/100] Starting: Task 1.1 — Spike
[RALPH LOOP - ITERATION 2/100] Completed: Task 1.1 — PROCEED decision
[RALPH LOOP - ITERATION 3/100] Starting: Task 1.2 — Project scaffolding
...
[RALPH LOOP - ITERATION N/100] All 14 tasks COMPLETE
```

---

## Completion Evidence

| Criterion | Status | Evidence |
|-----------|--------|---------|
| Build passes | [ ] | `build output` |
| All endpoints return correct responses | [ ] | API test output |
| E2E scenario passes | [ ] | Screenshot/log |
| Performance meets requirements | [ ] | Load test report |
| Documentation complete | [ ] | Docs URL |

---

*This report is produced by the Specum implement stage.*
*Update task statuses and evidence as implementation progresses.*
*Advance to Verify stage only when all Phase 4 criteria are met.*
"""
