"""
Specum requirements stage.

Transforms a goal string into structured requirements:
user stories, acceptance criteria, scope boundaries, and open questions.
Uses the ProductManagerAgent persona.
"""

from __future__ import annotations

from datetime import datetime
from typing import Optional


class RequirementsStage:
    """
    Requirements generation stage using a ProductManagerAgent persona.

    Takes a high-level goal and produces a structured requirements.md
    with user stories, acceptance criteria, constraints, and open questions.

    The output of this stage becomes the input for the DesignStage.
    """

    PERSONA = "ProductManagerAgent"

    def __init__(self, goal: str) -> None:
        """
        Initialize the requirements stage.

        Args:
            goal: The high-level goal to generate requirements for.
        """
        self.goal = goal
        self.generated_at = datetime.utcnow()

    def generate(self) -> str:
        """
        Generate the requirements artifact.

        Produces a complete requirements.md with:
        - Problem statement
        - User stories in Given/When/Then format
        - Acceptance criteria (numbered, testable)
        - Scope boundaries (in-scope and out-of-scope)
        - Assumptions that need validation
        - Open questions blocking implementation

        Returns:
            Requirements artifact as a markdown string.
        """
        return self._render_requirements()

    def _render_requirements(self) -> str:
        """Render the requirements markdown document."""
        return f"""# Requirements Specification

**Generated by:** {self.PERSONA}
**Date:** {self.generated_at.strftime('%Y-%m-%d %H:%M UTC')}
**Goal:** {self.goal}

---

## Problem Statement

{self._derive_problem_statement()}

## User Stories

{self._generate_user_stories()}

## Acceptance Criteria

{self._generate_acceptance_criteria()}

## Scope

### In Scope
{self._define_in_scope()}

### Out of Scope
{self._define_out_of_scope()}

## Constraints

{self._identify_constraints()}

## Assumptions

{self._list_assumptions()}

## Open Questions

{self._list_open_questions()}

---

*This document was produced by the Specum requirements stage.*
*Review and refine before advancing to the Design stage.*
"""

    def _derive_problem_statement(self) -> str:
        """Derive a structured problem statement from the goal."""
        return (
            f"We need to {self.goal.lower().rstrip('.')}.\n\n"
            f"This specification defines the requirements that any implementation must satisfy "
            f"to be considered complete. All acceptance criteria below must be met before "
            f"the implementation is considered done."
        )

    def _generate_user_stories(self) -> str:
        """Generate user story templates for the goal."""
        return (
            "<!-- SPECUM: Fill in concrete user stories for your goal -->\n\n"
            "1. **As a** user, **I want to** [primary action from goal], **so that** [business value].\n\n"
            "2. **As a** developer, **I want to** integrate this via a clean API, **so that** "
            "I can build on top of it without reading the implementation.\n\n"
            "3. **As an** operator, **I want to** monitor the system's behavior, **so that** "
            "I can detect and diagnose issues in production.\n\n"
            "4. **As an** administrator, **I want to** configure the system without code changes, "
            "**so that** I can adapt it to different environments."
        )

    def _generate_acceptance_criteria(self) -> str:
        """Generate testable acceptance criteria."""
        return (
            "<!-- SPECUM: Each criterion must be verifiable with concrete evidence -->\n\n"
            "1. **Given** the system is running, **when** a user performs the primary action, "
            "**then** the expected outcome occurs within acceptable latency (<2s for interactive operations).\n\n"
            "2. **Given** invalid input, **when** the user submits, **then** a clear error message "
            "is returned (not a 500 error) and no data is corrupted.\n\n"
            "3. **Given** a system restart, **when** the system comes back online, "
            "**then** all previously committed state is preserved.\n\n"
            "4. **Given** concurrent operations, **when** multiple users act simultaneously, "
            "**then** data consistency is maintained (no lost updates, no corruption).\n\n"
            "5. **Given** the feature is deployed, **when** an operator checks logs, "
            "**then** all significant operations are logged with sufficient context for debugging."
        )

    def _define_in_scope(self) -> str:
        """Define what is in scope."""
        return (
            "<!-- SPECUM: List specific deliverables -->\n"
            "- Core functionality as described in the goal\n"
            "- API/interface for programmatic access\n"
            "- Error handling for all defined error cases\n"
            "- Basic observability (logging, key metrics)\n"
            "- Documentation for the public interface"
        )

    def _define_out_of_scope(self) -> str:
        """Define what is explicitly out of scope."""
        return (
            "<!-- SPECUM: Explicit out-of-scope prevents scope creep -->\n"
            "- UI/frontend (unless explicitly part of the goal)\n"
            "- Performance optimization beyond baseline requirements\n"
            "- Migration of existing data (unless specified)\n"
            "- Mobile support (unless specified)\n"
            "- Internationalization (unless specified)"
        )

    def _identify_constraints(self) -> str:
        """Identify technical and business constraints."""
        return (
            "**Technical Constraints:**\n"
            "- Must integrate with existing system architecture\n"
            "- Must not break existing public APIs\n"
            "- Must handle concurrent load from multiple users\n\n"
            "**Business Constraints:**\n"
            "- Implementation must be maintainable by the current team\n"
            "- No new external service dependencies without approval\n\n"
            "**Security Constraints:**\n"
            "- All user input must be validated and sanitized\n"
            "- No secrets in source code\n"
            "- Authentication required for all non-public endpoints"
        )

    def _list_assumptions(self) -> str:
        """List assumptions that need validation."""
        return (
            "<!-- SPECUM: Assumptions that could invalidate this spec if wrong -->\n\n"
            "1. The existing authentication system can be reused (validate before design)\n"
            "2. Current database schema can accommodate the new feature without migration\n"
            "3. The performance requirements can be met with the current infrastructure\n"
            "4. Team has sufficient expertise to implement without external consultation"
        )

    def _list_open_questions(self) -> str:
        """List open questions that must be answered before implementation."""
        return (
            "<!-- SPECUM: These MUST be answered before advancing to Design -->\n\n"
            "1. [ ] What is the expected load (requests/second, concurrent users)?\n"
            "2. [ ] Are there SLA requirements (uptime, latency targets)?\n"
            "3. [ ] Who are the consumers of this feature (internal team, external customers)?\n"
            "4. [ ] What is the rollback plan if the deployment has issues?\n"
            "5. [ ] Are there data retention or compliance requirements?"
        )
