"""
Specum tasks stage.

Transforms the technical design into an ordered implementation task list
with phases, dependencies, and complexity estimates.
Uses the TaskPlannerAgent persona.
"""

from __future__ import annotations

from datetime import datetime
from typing import Optional


class TaskStage:
    """
    Task breakdown stage using a TaskPlannerAgent persona.

    Consumes the design artifact and produces a tasks.md with:
    - Numbered tasks organized into phases
    - Dependencies between tasks
    - Complexity estimates (S/M/L)
    - Verification checkpoints between phases

    The output of this stage becomes the input for the ImplementStage.
    """

    PERSONA = "TaskPlannerAgent"

    def __init__(self, goal: str, design_artifact: Optional[str] = None) -> None:
        """
        Initialize the task stage.

        Args:
            goal: The high-level goal being implemented.
            design_artifact: Content of the design.md from the previous stage.
        """
        self.goal = goal
        self.design = design_artifact or ""
        self.generated_at = datetime.utcnow()

    def generate(self) -> str:
        """
        Generate the tasks artifact.

        Returns:
            Tasks artifact as a markdown string with phased task breakdown.
        """
        return self._render_tasks()

    def _render_tasks(self) -> str:
        """Render the implementation task list."""
        return f"""# Implementation Task List

**Generated by:** {self.PERSONA}
**Date:** {self.generated_at.strftime('%Y-%m-%d %H:%M UTC')}
**Goal:** {self.goal}

---

## Risk Assessment

| Risk | Probability | Impact | Mitigation |
|------|------------|--------|------------|
| Unknown external API behavior | Medium | High | Spike task first (Task 1.1) |
| Data migration complexity | Low | High | Schema designed for backward compat |
| Performance under load | Medium | Medium | Load test in Phase 4 |

---

## Phase 1: Foundation (Prerequisite spike + infrastructure)

**Goal:** Validate unknowns and establish the project skeleton before building features.
**Verification:** Schema exists in DB, spike result is documented.

### Task 1.1: Proof-of-concept spike — validate critical assumptions
**Description:** Before committing to the design, validate the riskiest assumption (external API behavior, performance feasibility, or integration compatibility).
**Inputs:** Design document, access to external systems
**Outputs:** Spike result document with PROCEED or PIVOT decision
**Complexity:** M
**Depends on:** None

### Task 1.2: Project scaffolding and build setup
**Description:** Create the project structure, configure the build system, set up linting and formatting, establish the CI pipeline skeleton.
**Inputs:** Tech stack decisions from design
**Outputs:** Compilable/runnable skeleton project with CI passing
**Complexity:** S
**Depends on:** 1.1 (PROCEED decision)

### Task 1.3: Database schema and migration
**Description:** Implement the database schema from the design document. Create the migration files. Verify schema is backward compatible.
**Inputs:** Data model section of design.md
**Outputs:** Migration files, schema applied to dev database
**Complexity:** M
**Depends on:** 1.2

### Task 1.4: Repository layer
**Description:** Implement the data access layer with CRUD operations, pagination, and basic query patterns.
**Inputs:** Schema from 1.3, API contracts from design
**Outputs:** Repository classes with tests confirming correct SQL
**Complexity:** M
**Depends on:** 1.3

### ✓ Phase 1 Verification Checkpoint
Confirm before proceeding:
- [ ] Spike documented: PROCEED decision recorded
- [ ] Project builds and CI is green
- [ ] Schema migration runs successfully on clean DB
- [ ] Repository basic CRUD operations verified

---

## Phase 2: Core Business Logic

**Goal:** Implement domain layer and service layer without infrastructure coupling.
**Verification:** Business rules enforced correctly, service layer orchestrates correctly.

### Task 2.1: Domain model and business rules
**Description:** Implement core domain entities, value objects, and business rules. No infrastructure dependencies — pure domain logic only.
**Inputs:** Domain design from design.md
**Outputs:** Domain layer with business rule validation
**Complexity:** M
**Depends on:** 1.2

### Task 2.2: Service layer orchestration
**Description:** Implement the service layer that coordinates domain logic, repository access, and external service calls.
**Inputs:** Service design from design.md, repository from 1.4, domain from 2.1
**Outputs:** Service layer that passes integration scenarios
**Complexity:** M
**Depends on:** 1.4, 2.1

### Task 2.3: Error handling and validation
**Description:** Implement consistent error types, validation logic, and error propagation per the error handling strategy in design.md.
**Inputs:** Error strategy from design.md
**Outputs:** Error hierarchy, validation middleware, consistent error responses
**Complexity:** S
**Depends on:** 2.2

### ✓ Phase 2 Verification Checkpoint
- [ ] Business rules correctly enforce all constraints
- [ ] Service layer handles all success and error scenarios
- [ ] Error types are consistent throughout

---

## Phase 3: API Layer

**Goal:** Expose the business logic through the API contract.
**Verification:** All defined endpoints match contract exactly.

### Task 3.1: API routing and middleware
**Description:** Set up routing framework, authentication middleware, rate limiting, and request logging.
**Inputs:** API design from design.md
**Outputs:** Routing setup with middleware stack
**Complexity:** S
**Depends on:** 2.3

### Task 3.2: Implement API endpoints per contract
**Description:** Implement each endpoint defined in the API contract. Request validation, service delegation, response serialization.
**Inputs:** API contract from design.md, service layer from 2.2
**Outputs:** All endpoints returning correct responses per contract
**Complexity:** M
**Depends on:** 3.1, 2.2

### Task 3.3: API error responses
**Description:** Ensure all error cases return the correct HTTP status codes and error response format per the contract.
**Inputs:** Error strategy from design.md, endpoints from 3.2
**Outputs:** All error cases return correct format
**Complexity:** S
**Depends on:** 3.2

### ✓ Phase 3 Verification Checkpoint
- [ ] Each endpoint tested against the API contract specification
- [ ] All success cases return correct response format
- [ ] All error cases return correct status codes and messages

---

## Phase 4: Integration and Quality

**Goal:** Connect all layers, add observability, and validate non-functional requirements.
**Verification:** End-to-end flow works, system is observable.

### Task 4.1: End-to-end integration test
**Description:** Run a complete user flow from API request through service layer to database and back. Fix any integration issues.
**Inputs:** Running system with all layers from Phases 1-3
**Outputs:** Documented E2E scenario that passes
**Complexity:** M
**Depends on:** 3.3

### Task 4.2: Observability (logging, metrics)
**Description:** Add structured logging with correlation IDs, key operational metrics, and health check endpoint.
**Inputs:** Observability requirements from design
**Outputs:** All operations logged, metrics endpoint available
**Complexity:** S
**Depends on:** 4.1

### Task 4.3: Load and performance validation
**Description:** Run load test to verify system meets performance requirements. Fix any bottlenecks found.
**Inputs:** Performance requirements from requirements.md
**Outputs:** Load test results showing requirements are met
**Complexity:** M
**Depends on:** 4.1

### Task 4.4: Documentation
**Description:** Write API reference documentation, deployment guide, and operational runbook.
**Inputs:** Final API contracts, deployment setup
**Outputs:** Docs covering: API reference, quickstart, configuration, troubleshooting
**Complexity:** S
**Depends on:** 4.2

### ✓ Phase 4 Verification Checkpoint (Final Gate)
- [ ] E2E scenario passes in staging environment
- [ ] Performance meets requirements from load test
- [ ] All operations are logged with correlation IDs
- [ ] Documentation covers all public interfaces
- [ ] No known critical or high severity issues outstanding

---

## Summary

| Phase | Tasks | Complexity Total | Estimated Effort |
|-------|-------|-----------------|-----------------|
| 1: Foundation | 4 tasks | 3S + 1M | 1-2 days |
| 2: Business Logic | 3 tasks | 1S + 2M | 1-2 days |
| 3: API Layer | 3 tasks | 2S + 1M | 1 day |
| 4: Integration & Quality | 4 tasks | 2S + 2M | 1-2 days |
| **Total** | **14 tasks** | **8S + 6M** | **4-7 days** |

---

*This document was produced by the Specum tasks stage.*
*Review task ordering and dependencies before advancing to the Implement stage.*
"""
