"""
Specum verify stage.

Validates implementation completeness through evidence collection.
Issues a final PASS or FAIL verdict against the original acceptance criteria.
Uses the VerifierAgent persona.
"""

from __future__ import annotations

from datetime import datetime
from typing import Optional


class VerifyStage:
    """
    Verification stage using a VerifierAgent persona.

    Consumes the implementation report and validates it against:
    - Original acceptance criteria from requirements
    - API contract compliance from design
    - Evidence quality (not just claims)

    Issues a final PASS or FAIL verdict. FAIL includes specific
    gaps that must be addressed before the pipeline can complete.
    """

    PERSONA = "VerifierAgent"

    def __init__(self, goal: str, implementation_artifact: Optional[str] = None) -> None:
        """
        Initialize the verify stage.

        Args:
            goal: The high-level goal being verified.
            implementation_artifact: Content of implementation-report.md.
        """
        self.goal = goal
        self.implementation = implementation_artifact or ""
        self.generated_at = datetime.utcnow()

    def generate(self) -> str:
        """
        Generate the verification report artifact.

        Returns:
            Verification report as a markdown string with PASS/FAIL verdict.
        """
        return self._render_verification_report()

    def _render_verification_report(self) -> str:
        """Render the verification report document."""
        return f"""# Verification Report

**Generated by:** {self.PERSONA}
**Date:** {self.generated_at.strftime('%Y-%m-%d %H:%M UTC')}
**Goal:** {self.goal}

---

## VERDICT: [ ] PASS  [ ] FAIL

> Update this verdict after completing all criteria checks below.
> PASS requires ALL criteria to be met with evidence.
> FAIL requires at least one critical criterion unmet.

---

## Acceptance Criteria Verification

Each criterion from requirements.md must be verified with concrete evidence.

### Criterion 1: Primary action succeeds within latency target
- **Status:** [ ] PASS  [ ] FAIL  [ ] NOT TESTED
- **Evidence required:** API response showing <2s latency under normal load
- **Evidence provided:** [Link to test results or screenshot]
- **Notes:** [Any observations]

### Criterion 2: Invalid input returns clear error
- **Status:** [ ] PASS  [ ] FAIL  [ ] NOT TESTED
- **Evidence required:** API response showing 400 with field-specific error message
- **Evidence provided:** [curl output or screenshot]
- **Notes:**

### Criterion 3: State survives system restart
- **Status:** [ ] PASS  [ ] FAIL  [ ] NOT TESTED
- **Evidence required:** Data persists after service restart
- **Evidence provided:** [Test sequence showing persistence]
- **Notes:**

### Criterion 4: Concurrent operations maintain consistency
- **Status:** [ ] PASS  [ ] FAIL  [ ] NOT TESTED
- **Evidence required:** Concurrent load test shows no data corruption
- **Evidence provided:** [Load test results]
- **Notes:**

### Criterion 5: All operations are logged
- **Status:** [ ] PASS  [ ] FAIL  [ ] NOT TESTED
- **Evidence required:** Log output showing structured entries for all key operations
- **Evidence provided:** [Log samples]
- **Notes:**

---

## API Contract Compliance

Verify each endpoint matches the contract in design.md exactly.

| Endpoint | Contract Match | Status | Notes |
|----------|---------------|--------|-------|
| POST /api/v1/entities | [ ] | PASS/FAIL | |
| GET /api/v1/entities/:id | [ ] | PASS/FAIL | |
| GET /api/v1/entities | [ ] | PASS/FAIL | |
| Error format consistency | [ ] | PASS/FAIL | |

---

## Non-Functional Requirements

| Requirement | Target | Actual | Status |
|------------|--------|--------|--------|
| Response latency (p95) | <2s | [measured] | PASS/FAIL |
| Throughput | [target req/s] | [measured] | PASS/FAIL |
| Availability (uptime) | 99.9% | [measured] | PASS/FAIL |
| Error rate under load | <0.1% | [measured] | PASS/FAIL |

---

## Evidence Quality Assessment

| Evidence Type | Provided | Sufficient | Notes |
|--------------|---------|-----------|-------|
| Build output (passing) | [ ] | [ ] | |
| API test results | [ ] | [ ] | |
| E2E scenario recording | [ ] | [ ] | |
| Load test report | [ ] | [ ] | |
| Log samples | [ ] | [ ] | |
| Documentation link | [ ] | [ ] | |

---

## Gaps Found

*List any acceptance criteria, contract elements, or NFRs not yet met:*

1. [ ] [Gap description with specific evidence of what's missing]
2. [ ] [Gap description]

---

## Final Checklist

- [ ] All 5 acceptance criteria verified with evidence
- [ ] All API endpoints match contract
- [ ] Non-functional requirements met
- [ ] No known critical or high severity bugs
- [ ] Documentation complete and accurate
- [ ] Load test passed
- [ ] Zero regression failures

---

## Verdict Rationale

**If PASS:**
All acceptance criteria met with concrete evidence. API contract compliant.
Non-functional requirements validated. Ready for deployment.

**If FAIL:**
[Specific criteria not met — list with references to evidence gaps above]

---

*This report is produced by the Specum verify stage.*
*A PASS verdict completes the pipeline.*
*A FAIL verdict requires returning to the Implement stage to address gaps.*
"""
